ACM-5066 pool-destruction-status-is-inconsist
open-cluster-management/console pull request #2799
Opened 2023-04-24 17:20 UTC by jeswanke

Signed-off-by: John Swanke <jswanke@redhat.com>

2023-04-24 19:51 UTC, KevinFCormier requested changes
@jeswanke Can you please use the `AcmInlineStatus` component? In other places we do not use a `Label`.

2023-04-24 20:33 UTC, jeswanke commented
@KevinFCormier done

2023-04-24 20:48 UTC, KevinFCormier commented on frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
> +                return <AcmInlineStatus type={StatusType.progress} status={t('Destroying')} />
```suggestion
                return <AcmInlineStatus type={StatusType.progress} status={t('destroying')} />
```

For some reason the translation key starts with lower case.

2023-04-25 12:58 UTC, KevinFCormier commented
/lgtm

2023-04-25 13:02 UTC, merged