11501 discoveredclusters rbac
open-cluster-management/console pull request #496
Opened 2021-04-22 20:47 UTC by zkayyali812

https://github.com/open-cluster-management/backlog/issues/11501

2021-04-22 20:47 UTC, zkayyali812 commented
/hold

2021-04-26 02:10 UTC, showeimer commented on frontend/src/routes/Credentials/Credentials.tsx
> +    }
```js
const discoveryNamespace = props.discoveryConfigs?.find((config) => config.metadata.namespace === namespace)
return discoveryNamespace ?? ''
```

2021-04-26 17:18 UTC, cameronmwall submitted a review, later dismissed

2021-04-26 17:39 UTC, jamestalton requested changes

2021-04-26 17:39 UTC, jamestalton commented on frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
> +        header: 'Last active',
translations needed

2021-04-26 17:39 UTC, jamestalton commented on frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
> +        header: 'Infrastructure provider',
translations needed

2021-04-26 17:39 UTC, jamestalton commented on frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
> +        header: 'Distribution version',
translations needed

2021-04-26 17:39 UTC, jamestalton commented on frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
> +        header: 'Namespace',
translations needed

2021-04-26 17:39 UTC, jamestalton commented on frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
>          header: 'Status',
translations needed

2021-04-26 17:39 UTC, jamestalton commented on frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
>          header: 'Name',
translations needed

2021-04-26 17:39 UTC, jamestalton commented on frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
> +            plural="discovered clusters"
translations needed

2021-04-26 20:32 UTC, zkayyali812 commented
Closing due to soiling branch with bad DCO signoffs -  opened - https://github.com/open-cluster-management/console/pull/507 to contain fixes w/ proper signoffs

2021-04-26 20:32 UTC, closed without merging