update to be consistent with Patternfly guidelines
open-cluster-management/console pull request #636
Opened 2021-05-24 20:58 UTC by jamestalton

Signed-off-by: James Talton <jtalton@redhat.com>

2021-05-24 21:14 UTC, showeimer commented on frontend/public/locales/en/cluster.json
> +    "bulk.title.destroy": "Permanently sestroy clusters?",
destroy

2021-05-24 21:14 UTC, showeimer commented on frontend/src/routes/BareMetalAssets/BareMetalAsset.test.tsx
> +    test('can delete assets from batch action menu', async () => {
😂

2021-05-24 21:14 UTC, showeimer commented on frontend/public/locales/en/bma.json
> +    "modal.delete.title.batch": "Delete {{number}} bare metal assets",
Why is this one a number?

2021-05-27 03:08 UTC, swopebe commented
thanks for pulling me in, added some review comments, sorry took a couple days to get to this.

2021-06-01 14:07 UTC, swopebe requested changes

2021-06-01 17:29 UTC, showeimer approved these changes

2021-06-01 17:30 UTC, merged