cluster delete rbac fix
open-cluster-management/console pull request #773
Opened 2021-07-08 16:43 UTC by Randy424

Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>

https://github.com/open-cluster-management/backlog/issues/12709

2021-07-08 17:36 UTC, Randy424 commented
/hold

2021-07-08 17:40 UTC, Randy424 commented
@jamestalton 
After those last changes we hit this after destroy button is pressed:

<img width="747" alt="Screen Shot 2021-07-08 at 1 39 21 PM" src="https://user-images.githubusercontent.com/21374229/124967005-ea8aa800-dff1-11eb-8956-a27c503e36a9.png">

...though, Destroy still succeeds

2021-07-08 18:24 UTC, Randy424 commented
/unhold
working now

2021-07-08 21:37 UTC, jamestalton requested changes

2021-07-08 21:37 UTC, jamestalton commented on frontend/src/lib/delete-cluster.ts
> +                if (promisesSettledResult[1]?.status === 'rejected') {
we need to switch around the logic as it expects promisesSettledResult[1] to be for the cluster deployment and
promisesSettledResult[0] will now be for the cluster deployment

2021-07-12 13:51 UTC, jamestalton approved these changes
lgtm

2021-07-12 13:51 UTC, merged