Aws gov yaml changes
open-cluster-management/console pull request #877
Opened 2021-09-24 02:24 UTC by Randy424

2021-09-24 12:18 UTC, Randy424 commented
/hold

2021-09-28 20:56 UTC, Randy424 commented
/cc @KevinFCormier @jamestalton @cadawson

2021-09-28 20:57 UTC, Randy424 commented
@cadawson This PR could benefit from a preemptive review from doc team! If you have the time feel free to take a look. See the screenshots below for context.

![Screen Shot 2021-09-28 at 4 54 54 PM](https://user-images.githubusercontent.com/21374229/135164441-d125e0c9-9384-4a1a-9e77-f5ddc11cae7c.png)


![Screen Shot 2021-09-28 at 4 55 02 PM](https://user-images.githubusercontent.com/21374229/135164458-a42d2e8a-72c5-450d-bec9-3a996a178ca5.png)

2021-10-01 19:06 UTC, KevinFCormier requested changes
Looks good! I just found one little typo.

2021-10-01 19:06 UTC, KevinFCormier commented on frontend/public/locales/en/create.json
> +    "creation.aws.subnet.subtitle": "Subets",
```suggestion
    "creation.aws.subnet.subtitle": "Subnets",
```

2021-10-01 20:51 UTC, KevinFCormier commented
/lgtm

2021-10-01 21:43 UTC, Randy424 commented
/unhold

2021-10-01 21:44 UTC, merged