lbFloatingIP addition, Kuryr addition
open-cluster-management/console pull request #983
Opened 2021-11-16 19:04 UTC by Randy424

Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>

2021-11-16 19:27 UTC, Randy424 commented
/cc @KevinFCormier @jeswanke

2021-12-08 02:58 UTC, Randy424 commented
/retest

2021-12-08 16:21 UTC, Randy424 commented
/cc @jamestalton (dco issues)

2021-12-08 18:14 UTC, KevinFCormier requested changes
See inline comments. Also a couple other concerns:

1. I am not sure of the meaning of 'lt' and 'gt' in functions `isHidden_lt_OCP48` and `isHidden_gt_OCP46`. I had guessed that it meant "less than" or "greater than"... but `isHidden_gt_OCP46` only checks for 4.6 (which is fine if we are not considering older versions), and `isHidden_lt_OCP48` checks for 4.8, 4.9, and 4.10. So that makes sense as well, but actually, shouldn't apiFloatingIP check for `!ishidden_gt_OCP46`. Currently if I select OCP 4.7, it does not show.
2. The handlebars templating is based on whether the value is present, so if I enter an lbFloatingIP, and then change my OCP version, it will still be present in the YAML when I enter an apiFloatingIP. I wonder if these could really be the same form element, with just the labels and YAML key changing when the version changes? Might be a question for @jeswanke.

2021-12-08 18:14 UTC, KevinFCormier commented on frontend/public/locales/en/create.json
> +    "placeholder.creation.ocp.cluster.ost.lb.floating.ip": "Enter LB floating IP",
On main branch, `create.json` file is obsolete. Please add these in `plugin__acm-plugin.json`

2021-12-08 18:14 UTC, KevinFCormier commented on frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
> +    apiFloatingIP: {{{../../apiFloatingIP}}}
I think `apiFloatingIP` should be conditional as well.

2021-12-13 21:41 UTC, Randy424 commented
@KevinFCormier 
Demo of recent change:

https://user-images.githubusercontent.com/21374229/145893091-ea672c25-4882-4be5-ac52-a97ddec6a9e9.mov

2021-12-13 21:47 UTC, KevinFCormier commented on frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
> +    //NOTE: We will need to adjust this in the future for new OCP versions!
This comment is not really accurate... the function checks for anything 4.6 (or older) but 4.6 is the oldest we've ever supported deploying, so we will not need to add new versions here.

2021-12-13 21:52 UTC, KevinFCormier commented
/lgtm

2021-12-13 21:52 UTC, KevinFCormier approved these changes

2021-12-13 22:40 UTC, merged